#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update -y -qq

sudo apt-get install nginx -y

sudo service nginx start

# Allow HTTP traffic through firewall
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

service nginx start
