#!/usr/bin/env bash
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/new
echo "127.0.0.2		localhost" > ~/new
echo "8.8.8.8		facebook.com" >> ~/new
cp -f ~/new /etc/hosts
